apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  labels:
    app: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: my-haproxy-image:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/
      volumes:
        - name: haproxy-config
          configMap:
            name: haproxy-config
